### ISSUE TITLE
Maya side?

### ISSUE THREAD

**Issue by antithing** [A7ocin/FaceAnimator#1]
Hi! This looks like a  very interesting project. Sending dlib landmarks to maya is cool. :)

What do you have on the maya side? Is there an already rigged face? A python script to connect to the stream?

Thanks!

**Comment by A7ocin** [comment]
Hello there! Thank you for your interest.

I just updated the README in order to make everyone capable of testing the tool.
I included the rigged face model as well as the MEL script for the connection.

Again, thank you for your interest, please let me know if you succeed executing the tool or if you encounter any issue. Any suggestion is really appreciated.

Nicola.

**Comment by antithing** [comment]
Thank you again! I have it working. :) Once I have used it a bit more I will report back.
